Update classroom.yml

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -42,11 +42,10 @@ jobs:
           javac main.java || exit 1
         command: |
           if [ "${{ steps.s_value.outputs.points }}" -eq 5 ]; then
-            exit 0
-            echo "Scanner points are correctly set to 5."
+            echo "✅ Test Passed)."
           else
-            echo "Scanner points are not 5."
-            exit 1  # Fail the workflow if points are not 5
+            echo "S❌ Test Failed"
+            exit 1
           fi
 
         timeout: 10
