Update classroom.yml

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -27,8 +27,10 @@ jobs:
       run: | 
         if grep -q 'java.util.Scanner input = new java.util.Scanner(System.in);' main.java; then 
            echo "scanner_points=5" >> $GITHUB_ENV 
+           echo "scanner_points=5" >> $GITHUB_OUTPUT
         else 
            echo "scanner_points=0" >> $GITHUB_ENV 
+           echo "scanner_points=0" >> $GITHUB_OUTPUT
         exit 1 
         fi 
 
@@ -40,10 +42,11 @@ jobs:
         setup-command: |
           javac main.java || exit 1
         command: |
-          if [ "$scanner_points" -q 5 ]; then
-            exit 0
+          if [ "${{ steps.scanner_check.outputs.scanner_points }}" -eq 5 ]; then
+            echo "Scanner points are correctly set to 5."
           else
-            exit 1
+            echo "Scanner points are not 5."
+            exit 1  # Fail the workflow if points are not 5
           fi
           # if grep -q 'java.util.Scanner input = new java.util.Scanner(System.in);' main.java; then
           #     exit 0  
