Update classroom.yml

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -25,13 +25,16 @@ jobs:
     - name: temp_values
       id: s_value 
       run: | 
-        if grep -q 'java.util.Scanner input = new java.util.Scanner(System.in);' main.java; then 
-           echo "points=5" >> $GITHUB_ENV 
-           echo "points=5" >> $GITHUB_OUTPUT
-        else 
-           echo "points=0" >> $GITHUB_ENV 
-           echo "points=0" >> $GITHUB_OUTPUT
-        fi 
+        grep -q 'java.util.Scanner input = new java.util.Scanner(System.in);' main.java \
+         && echo "scanner_points=5" >> $GITHUB_ENV || echo "scanner_points=0" >> $GITHUB_ENV
+
+        # if grep -q 'java.util.Scanner input = new java.util.Scanner(System.in);' main.java; then 
+        #    echo "points=5" >> $GITHUB_ENV 
+        #    echo "points=5" >> $GITHUB_OUTPUT
+        # else 
+        #    echo "points=0" >> $GITHUB_ENV 
+        #    echo "points=0" >> $GITHUB_OUTPUT
+        # fi 
 
     - name: Scanner_test
       id: scanner_test
@@ -41,12 +44,18 @@ jobs:
         setup-command: |
           javac main.java || exit 1
         command: |
-          if [ "${{ steps.s_value.outputs.points }}" -eq 5 ]; then
-            echo "✅ Test Passed)."
+          if [ "$scanner_points" -eq 5 ]; then
+            echo "✅ Passed: Scanner usage correct."
           else
-            echo "S❌ Test Failed"
+            echo "❌ Failed: Incorrect Scanner usage. Ensure 'java.util.Scanner' is properly declared."
             exit 1
           fi
+          # if [ "${{ steps.s_value.outputs.points }}" -eq 5 ]; then
+          #   echo "✅ Test Passed)."
+          # else
+          #   echo "S❌ Test Failed"
+          #   exit 1
+          # fi
 
         timeout: 10
         max-score: 5
